<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="org.springframework.scheduling.annotation.EnableAsyncTests" tests="17" skipped="0" failures="0" errors="0" timestamp="2021-01-22T01:38:52" hostname="SUPERMAN" time="0.909">
  <properties/>
  <testcase name="customAsyncAnnotationIsPropagated()" classname="org.springframework.scheduling.annotation.EnableAsyncTests" time="0.011"/>
  <testcase name="properExceptionForResolvedProxyDependencyMismatch()" classname="org.springframework.scheduling.annotation.EnableAsyncTests" time="0.011"/>
  <testcase name="customExecutorConfig()" classname="org.springframework.scheduling.annotation.EnableAsyncTests" time="0.062"/>
  <testcase name="aspectModeAspectJAttemptsToRegisterAsyncAspect()" classname="org.springframework.scheduling.annotation.EnableAsyncTests" time="0.003"/>
  <testcase name="proxyingOccurs()" classname="org.springframework.scheduling.annotation.EnableAsyncTests" time="0.011"/>
  <testcase name="asyncProcessorIsOrderedLowestPrecedenceByDefault()" classname="org.springframework.scheduling.annotation.EnableAsyncTests" time="0.007"/>
  <testcase name="exceptionThrownWithBeanNotOfRequiredTypeRootCause()" classname="org.springframework.scheduling.annotation.EnableAsyncTests" time="0.026"/>
  <testcase name="customExecutorBeanConfigWithThrowsException()" classname="org.springframework.scheduling.annotation.EnableAsyncTests" time="0.046"/>
  <testcase name="customExecutorBeanConfig()" classname="org.springframework.scheduling.annotation.EnableAsyncTests" time="0.062"/>
  <testcase name="properExceptionForExistingProxyDependencyMismatch()" classname="org.springframework.scheduling.annotation.EnableAsyncTests" time="0.016"/>
  <testcase name="findOnInterfaceWithInterfaceProxy()" classname="org.springframework.scheduling.annotation.EnableAsyncTests" time="0.057"/>
  <testcase name="findOnInterfaceWithCglibProxy()" classname="org.springframework.scheduling.annotation.EnableAsyncTests" time="0.123"/>
  <testcase name="customExecutorBean()" classname="org.springframework.scheduling.annotation.EnableAsyncTests" time="0.064"/>
  <testcase name="customExecutorConfigWithThrowsException()" classname="org.springframework.scheduling.annotation.EnableAsyncTests" time="0.053"/>
  <testcase name="proxyingOccursWithMockitoStub()" classname="org.springframework.scheduling.annotation.EnableAsyncTests" time="0.062"/>
  <testcase name="withAsyncBeanWithExecutorQualifiedByName()" classname="org.springframework.scheduling.annotation.EnableAsyncTests" time="0.276"/>
  <testcase name="orderAttributeIsPropagated()" classname="org.springframework.scheduling.annotation.EnableAsyncTests" time="0.014"/>
  <system-out><![CDATA[09:38:52.034 [Test worker] WARN  o.s.c.a.AnnotationConfigApplicationContext - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'enableAsyncTests.AsyncBeanUser': Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.BeanNotOfRequiredTypeException: Bean named 'asyncBean' is expected to be of type 'org.springframework.scheduling.annotation.EnableAsyncTests$AsyncBean' but was actually of type 'com.sun.proxy.$Proxy235'
09:38:52.099 [Test worker] WARN  o.s.c.a.AnnotationConfigApplicationContext - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanDefinitionStoreException: Failed to process import candidates for configuration class [org.springframework.scheduling.annotation.EnableAsyncTests$AspectJAsyncAnnotationConfig]; nested exception is java.io.FileNotFoundException: class path resource [org/springframework/scheduling/aspectj/AspectJAsyncConfiguration.class] cannot be opened because it does not exist
09:38:52.144 [Test worker] WARN  o.s.c.a.AnnotationConfigApplicationContext - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'user' defined in org.springframework.scheduling.annotation.EnableAsyncTests$UserConfiguration: Unsatisfied dependency expressed through method 'user' parameter 0; nested exception is org.springframework.beans.factory.BeanNotOfRequiredTypeException: Bean named 'asyncBean' is expected to be of type 'org.springframework.scheduling.annotation.EnableAsyncTests$AsyncBeanWithInterface' but was actually of type 'com.sun.proxy.$Proxy235'
09:38:52.269 [Test worker] WARN  o.s.c.a.AnnotationConfigApplicationContext - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'enableAsyncTests.AsyncBeanUser': Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.BeanNotOfRequiredTypeException: Bean named 'asyncBean' is expected to be of type 'org.springframework.scheduling.annotation.EnableAsyncTests$AsyncBean' but was actually of type 'com.sun.proxy.$Proxy235'
]]></system-out>
  <system-err><![CDATA[Jan 22, 2021 9:38:52 AM ClientIntermediary close
INFO: java.io.IOException: The connection is not currently established.
java.io.IOException: The connection is not currently established.
	at com.sun.jmx.remote.generic.ClientSynchroMessageConnectionImpl.checkState(ClientSynchroMessageConnectionImpl.java:617)
	at com.sun.jmx.remote.generic.ClientSynchroMessageConnectionImpl.sendOneWay(ClientSynchroMessageConnectionImpl.java:202)
	at javax.management.remote.generic.GenericConnector.close(GenericConnector.java:300)
	at javax.management.remote.generic.GenericConnector.close(GenericConnector.java:271)
	at javax.management.remote.generic.ClientIntermediary$GenericClientCommunicatorAdmin.doStop(ClientIntermediary.java:897)
	at com.sun.jmx.remote.opt.internal.ClientCommunicatorAdmin.restart(ClientCommunicatorAdmin.java:172)
	at com.sun.jmx.remote.opt.internal.ClientCommunicatorAdmin.gotIOException(ClientCommunicatorAdmin.java:73)
	at javax.management.remote.generic.GenericConnector$RequestHandler.execute(GenericConnector.java:662)
	at com.sun.jmx.remote.generic.ClientSynchroMessageConnectionImpl$RemoteJob.run(ClientSynchroMessageConnectionImpl.java:568)
	at com.sun.jmx.remote.opt.util.ThreadService$ThreadServiceJob.run(ThreadService.java:248)
	at com.sun.jmx.remote.opt.util.JobExecutor.run(JobExecutor.java:99)

Jan 22, 2021 9:38:52 AM ClientIntermediary close
INFO: java.io.IOException: The connection is not currently established.
java.io.IOException: The connection is not currently established.
	at com.sun.jmx.remote.generic.ClientSynchroMessageConnectionImpl.checkState(ClientSynchroMessageConnectionImpl.java:617)
	at com.sun.jmx.remote.generic.ClientSynchroMessageConnectionImpl.sendOneWay(ClientSynchroMessageConnectionImpl.java:202)
	at javax.management.remote.generic.GenericConnector.close(GenericConnector.java:300)
	at javax.management.remote.generic.GenericConnector.close(GenericConnector.java:271)
	at javax.management.remote.generic.ClientIntermediary$GenericClientCommunicatorAdmin.doStop(ClientIntermediary.java:897)
	at com.sun.jmx.remote.opt.internal.ClientCommunicatorAdmin.restart(ClientCommunicatorAdmin.java:172)
	at com.sun.jmx.remote.opt.internal.ClientCommunicatorAdmin.gotIOException(ClientCommunicatorAdmin.java:73)
	at javax.management.remote.generic.GenericConnector$RequestHandler.execute(GenericConnector.java:662)
	at com.sun.jmx.remote.generic.ClientSynchroMessageConnectionImpl$RemoteJob.run(ClientSynchroMessageConnectionImpl.java:568)
	at com.sun.jmx.remote.opt.util.ThreadService$ThreadServiceJob.run(ThreadService.java:248)
	at com.sun.jmx.remote.opt.util.JobExecutor.run(JobExecutor.java:99)

]]></system-err>
</testsuite>
