<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="org.springframework.scheduling.annotation.AsyncExecutionTests" tests="18" skipped="0" failures="0" errors="0" timestamp="2021-01-22T01:38:51" hostname="SUPERMAN" time="0.546">
  <properties/>
  <testcase name="asyncClass()" classname="org.springframework.scheduling.annotation.AsyncExecutionTests" time="0.125"/>
  <testcase name="asyncMethods()" classname="org.springframework.scheduling.annotation.AsyncExecutionTests" time="0.102"/>
  <testcase name="asyncMethodsInInterface()" classname="org.springframework.scheduling.annotation.AsyncExecutionTests" time="0.006"/>
  <testcase name="asyncClassWithInterface()" classname="org.springframework.scheduling.annotation.AsyncExecutionTests" time="0.013"/>
  <testcase name="asyncPrototypeClassListener()" classname="org.springframework.scheduling.annotation.AsyncExecutionTests" time="0.021"/>
  <testcase name="dynamicAsyncMethodsInInterfaceWithPostProcessor()" classname="org.springframework.scheduling.annotation.AsyncExecutionTests" time="0.039"/>
  <testcase name="asyncMethodsInInterfaceWithPostProcessor()" classname="org.springframework.scheduling.annotation.AsyncExecutionTests" time="0.004"/>
  <testcase name="asyncClassWithInterfaceAndPostProcessor()" classname="org.springframework.scheduling.annotation.AsyncExecutionTests" time="0.004"/>
  <testcase name="dynamicAsyncInterfaceWithPostProcessor()" classname="org.springframework.scheduling.annotation.AsyncExecutionTests" time="0.055"/>
  <testcase name="asyncInterfaceWithPostProcessor()" classname="org.springframework.scheduling.annotation.AsyncExecutionTests" time="0.029"/>
  <testcase name="dynamicAsyncInterface()" classname="org.springframework.scheduling.annotation.AsyncExecutionTests" time="0.059"/>
  <testcase name="asyncClassListener()" classname="org.springframework.scheduling.annotation.AsyncExecutionTests" time="0.013"/>
  <testcase name="asyncClassWithPostProcessor()" classname="org.springframework.scheduling.annotation.AsyncExecutionTests" time="0.002"/>
  <testcase name="asyncMethodsWithQualifier()" classname="org.springframework.scheduling.annotation.AsyncExecutionTests" time="0.033"/>
  <testcase name="asyncMethodsWithQualifierThroughInterface()" classname="org.springframework.scheduling.annotation.AsyncExecutionTests" time="0.02"/>
  <testcase name="asyncMethodListener()" classname="org.springframework.scheduling.annotation.AsyncExecutionTests" time="0.013"/>
  <testcase name="asyncMethodsThroughInterface()" classname="org.springframework.scheduling.annotation.AsyncExecutionTests" time="0.003"/>
  <testcase name="asyncInterface()" classname="org.springframework.scheduling.annotation.AsyncExecutionTests" time="0.003"/>
  <system-out><![CDATA[09:38:51.952 [e0-1] ERROR o.s.a.i.SimpleAsyncUncaughtExceptionHandler - Unexpected exception occurred invoking async method: public void org.springframework.scheduling.annotation.AsyncExecutionTests$AsyncMethodWithQualifierBean.doNothing(int)
org.opentest4j.AssertionFailedError: 
Expecting value to be true but was false
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_181]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_181]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_181]
	at org.springframework.scheduling.annotation.AsyncExecutionTests$AsyncMethodWithQualifierBean.doNothing(AsyncExecutionTests.java:478) ~[test/:?]
	at org.springframework.scheduling.annotation.AsyncExecutionTests$AsyncMethodWithQualifierBean$$FastClassBySpringCGLIB$$85bd9822.invoke(<generated>) ~[test/:?]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.3.4-SNAPSHOT.jar:5.3.4-SNAPSHOT]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:779) ~[spring-aop-5.3.4-SNAPSHOT.jar:?]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.3.4-SNAPSHOT.jar:?]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750) ~[spring-aop-5.3.4-SNAPSHOT.jar:?]
	at org.springframework.aop.interceptor.AsyncExecutionInterceptor.lambda$invoke$0(AsyncExecutionInterceptor.java:115) ~[spring-aop-5.3.4-SNAPSHOT.jar:5.3.4-SNAPSHOT]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_181]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_181]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_181]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
09:38:51.972 [e0-1] ERROR o.s.a.i.SimpleAsyncUncaughtExceptionHandler - Unexpected exception occurred invoking async method: public void org.springframework.scheduling.annotation.AsyncExecutionTests$AsyncMethodWithQualifierBean.doNothing(int)
org.opentest4j.AssertionFailedError: 
Expecting value to be true but was false
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_181]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_181]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_181]
	at org.springframework.scheduling.annotation.AsyncExecutionTests$AsyncMethodWithQualifierBean.doNothing(AsyncExecutionTests.java:478) ~[test/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_181]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_181]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_181]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_181]
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:344) ~[spring-aop-5.3.4-SNAPSHOT.jar:5.3.4-SNAPSHOT]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198) ~[spring-aop-5.3.4-SNAPSHOT.jar:?]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.3.4-SNAPSHOT.jar:?]
	at org.springframework.aop.interceptor.AsyncExecutionInterceptor.lambda$invoke$0(AsyncExecutionInterceptor.java:115) ~[spring-aop-5.3.4-SNAPSHOT.jar:5.3.4-SNAPSHOT]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_181]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_181]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_181]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
]]></system-out>
  <system-err><![CDATA[Jan 22, 2021 9:38:51 AM ClientCommunicatorAdmin restart
WARNING: Failed to restart: java.net.ConnectException: Connection refused: connect
Jan 22, 2021 9:38:51 AM ClientCommunicatorAdmin restart
WARNING: Failed to restart: java.net.ConnectException: Connection refused: connect
]]></system-err>
</testsuite>
